### ISSUE TITLE
Prebuilt binaries/apks

### ISSUE THREAD

**Issue by xdpirate** [fj-gruenewald/eazyffmpeg-android-app#1]
Hey - this looks like a great project and exactly what I am looking for to work with videos on the go without having to type out long ffmpeg commands in Termux (ugh). Unfortunately I get a bunch of gradle and java errors when I open it in Android Studio for building, probably due to the age of the environment the project was made in (I am also on Linux), meaning I am unable to build it without significant effort. Is there any chance the built APK could be published in Releases, for example?

**Comment by fj-gruenewald** [comment]
Hey Xdpirate, what kind of gradel errors do you get? Unfortunately and because of the time that has passed, im not having the apk on my phone anymore, nor do I have the apk on my computer. I would also have to figure out the errors and build the apk again. Greetings

**Comment by kityr** [comment]
@xdpirate @fj-gruenewald I forked the project and managed to compile it using github actions, apks are available as action artifacts. Hope they actually work heh

Published them in a release as well

**Comment by xdpirate** [comment]
@kityr Thank you!
